version: '3.8'

services:
  app:
    build: ./
    container_name: socket-collector
    restart: unless-stopped
    environment:
      ticker_data_save: none
      spring.datasource.url: jdbc:postgresql://localhost:5432/postgres
      spring_datasource_username: $spring_datasource_username
      spring_datasource_password: $spring_datasource_password
#    ports:
#      - "8081:8080"
    volumes:
      - ./docker-output-data:/output-data