version: '3.8'

services:
  socket-collector:
    build: ./
    container_name: socket-collector
    environment:
      output-path: "output-data"
    ports:
      - "8080:8080"
    volumes:
      - ./docker-output-data:/output-data